### ISSUE TITLE
JuliaBox example not working

### ISSUE THREAD

**Issue by mturok** [tanmaykm/Juliaset.jl#1]
Tried following the example as described with juliabox.org, and I just get a 404 error.

Is the description in the README correct, and I should be able to navigate to:  `https://api.juliabox.org/<api_name>/juliaset` ?

Michael

**Comment by tanmaykm** [comment]
Yes, that should work.
Something like: https://api.juliabox.org/juliaset/juliaset/

The first few requests can time out though, because by default api processors terminate when not used, and it may take some time to start them up.

**Comment by mturok** [comment]
Haven't seen it work yet.  Would I expect to see a process for the api if I
do a ps in the console?    Note that I am trying this on juliabox.org, in
addition to my local build.

**Comment by mturok** [comment]
....also, in my local build, I'm seeing an error in `JuliaBox/webserver/logs/error.log`:

```
2015/11/05 04:49:12 [error] 5#0: *235 lua entry thread aborted: runtime error: /jboxweb/openresty/lualib/juliabox/router.lua:311: attempt to get length of local 'match' (a nil value)
stack traceback:
coroutine 0:
    /jboxweb/openresty/lualib/juliabox/router.lua: in function 'api_route'
    access_by_lua(jbox_api_router.incl:6):3: in function <access_by_lua(jbox_api_router.incl:6):1>, client: 127.0.0.1, server: api.*, request: "GET /mturok_juliaset/juliaset HTTP/1.1", host: "api.mturok-virtualbox.blackrock.com"
```

**Comment by tanmaykm** [comment]
Hmm... I was able to get https://api.juliabox.org/juliaset/juliaset/ after a couple of attempts.
Not sure about the error log... need to look it up.

You should be able to see a docker container start up to serve the api when a request is submitted.

**Comment by mturok** [comment]
Thanks for all the help.   Can I ask a couple more questions?
- what was your exact api name and command?
- when you made a couple of attempts, what error messages did you initially see?

Michael

**Comment by mturok** [comment]
Hmm....when I click on your exact api link above, I do see a
juliaset.....am I looking at your api endpoint?

**Comment by tanmaykm** [comment]
My api name is `juliaset` and the command is:

```
Pkg.clone("https://github.com/tanmaykm/Juliaset.jl.git"); using Juliaset; Juliaset.serve_juliabox();
```

I saw the "408: Request Timeout" error till the api container was initializing.

**Comment by mturok** [comment]
Will try again when back at a monitor.  Thank you for all the
pointers...this is really great work!

**Comment by mturok** [comment]
Okay - looks like you are relying upon the trailing slash in the url.  I'm good.
